name: Build my Personal Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build MkDocs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.3
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      - name: Build Source Code
        run: mkdocs build --clean
      - name: Package and Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"
 
  deploy:
    needs: build
    name: Deploy MkDocs to GitHub Pages
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4